# Estas são as contas GitHub patrocinadas suportadas
github: [jhonslife]

# Plataformas de financiamento (quando disponíveis)
# patreon: arkheioncorp
# open_collective: tiktrend-finder
# ko_fi: arkheioncorp
# tidelift: npm/tiktrend-finder

# Página personalizada de doação
custom: ["https://arkheioncorp.com/donate"]
