"""add_composite_indices

Revision ID: f8c935eb4759
Revises: 003
Create Date: 2025-11-26 11:21:03.132168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8c935eb4759'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('idx_user_favorites_user_id', table_name='user_favorites')
    op.drop_table('user_favorites')
    op.drop_index('idx_api_logs_created_at', table_name='api_logs')
    op.drop_index('idx_api_logs_endpoint', table_name='api_logs')
    op.drop_index('idx_api_logs_user_id', table_name='api_logs')
    op.drop_table('api_logs')
    op.drop_index('idx_daily_stats_date', table_name='daily_stats')
    op.drop_table('daily_stats')
    op.add_column('copy_history', sa.Column('product_title', sa.String(length=500), nullable=False))
    op.add_column('copy_history', sa.Column('copy_type', sa.String(length=50), nullable=False))
    op.add_column('copy_history', sa.Column('tone', sa.String(length=50), nullable=False))
    op.add_column('copy_history', sa.Column('copy_text', sa.Text(), nullable=False))
    op.drop_constraint('copy_history_product_id_fkey', 'copy_history', type_='foreignkey')
    op.alter_column('copy_history', 'product_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               nullable=False)
    op.drop_index('idx_copy_history_user', table_name='copy_history')
    op.create_index('ix_copy_history_user_date', 'copy_history', ['user_id', 'created_at'], unique=False)
    op.drop_constraint('copy_history_user_id_fkey', 'copy_history', type_='foreignkey')
    # op.drop_constraint('copy_history_product_id_fkey', 'copy_history', type_='foreignkey') # Moved up
    op.create_foreign_key(None, 'copy_history', 'users', ['user_id'], ['id'])
    op.drop_column('copy_history', 'template_used')
    op.drop_column('copy_history', 'generated_title')
    op.drop_column('copy_history', 'generated_description')
    op.drop_column('copy_history', 'original_description')
    op.drop_column('copy_history', 'original_title')
    op.drop_column('copy_history', 'tokens_used')
    op.add_column('license_devices', sa.Column('hwid', sa.String(length=255), nullable=False))
    op.add_column('license_devices', sa.Column('app_version', sa.String(length=50), nullable=True))
    op.add_column('license_devices', sa.Column('first_seen_at', sa.DateTime(), nullable=True))
    op.add_column('license_devices', sa.Column('last_seen_at', sa.DateTime(), nullable=True))
    op.add_column('license_devices', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('license_devices', sa.Column('deactivated_at', sa.DateTime(), nullable=True))
    op.add_column('license_devices', sa.Column('deactivation_reason', sa.String(length=255), nullable=True))
    op.drop_index('idx_license_devices_license_id', table_name='license_devices')
    op.drop_constraint('license_devices_license_id_device_id_key', 'license_devices', type_='unique')
    op.create_unique_constraint('uq_license_device', 'license_devices', ['license_id', 'hwid'])
    op.drop_constraint('license_devices_license_id_fkey', 'license_devices', type_='foreignkey')
    op.create_foreign_key(None, 'license_devices', 'licenses', ['license_id'], ['id'])
    op.drop_column('license_devices', 'last_seen')
    op.drop_column('license_devices', 'device_name')
    op.drop_column('license_devices', 'device_id')
    op.drop_column('license_devices', 'created_at')
    op.drop_column('license_devices', 'device_info')
    op.add_column('licenses', sa.Column('activated_at', sa.DateTime(), nullable=True))
    op.add_column('licenses', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('licenses', sa.Column('auto_renew', sa.Boolean(), nullable=True))
    op.add_column('licenses', sa.Column('payment_id', sa.String(length=255), nullable=True))
    op.add_column('licenses', sa.Column('last_payment_id', sa.String(length=255), nullable=True))
    op.add_column('licenses', sa.Column('deactivation_reason', sa.String(length=255), nullable=True))
    op.add_column('licenses', sa.Column('deactivated_at', sa.DateTime(), nullable=True))
    op.alter_column('licenses', 'license_key',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_index('idx_licenses_license_key', table_name='licenses')
    op.drop_index('idx_licenses_status', table_name='licenses')
    op.drop_index('idx_licenses_user_id', table_name='licenses')
    op.drop_constraint('licenses_license_key_key', 'licenses', type_='unique')
    op.create_index(op.f('ix_licenses_license_key'), 'licenses', ['license_key'], unique=True)
    op.drop_constraint('licenses_user_id_fkey', 'licenses', type_='foreignkey')
    op.create_foreign_key(None, 'licenses', 'users', ['user_id'], ['id'])
    op.drop_column('licenses', 'status')
    op.drop_column('licenses', 'current_devices')
    op.drop_column('licenses', 'started_at')
    op.drop_column('licenses', 'features')
    op.add_column('payments', sa.Column('plan', sa.String(length=50), nullable=False))
    op.alter_column('payments', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('payments', 'payment_method',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_index('idx_payments_external_id', table_name='payments')
    op.drop_index('idx_payments_status', table_name='payments')
    op.drop_index('idx_payments_user_id', table_name='payments')
    op.drop_constraint('payments_external_id_key', 'payments', type_='unique')
    op.drop_constraint('payments_user_id_fkey', 'payments', type_='foreignkey')
    op.drop_constraint('payments_license_id_fkey', 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'users', ['user_id'], ['id'])
    op.drop_column('payments', 'metadata')
    op.drop_column('payments', 'paid_at')
    op.drop_column('payments', 'license_id')
    op.add_column('products', sa.Column('tiktok_id', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('currency', sa.String(length=10), nullable=True))
    op.add_column('products', sa.Column('subcategory', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('seller_name', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('seller_rating', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('product_rating', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('reviews_count', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('sales_7d', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('sales_30d', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('commission_rate', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('video_url', sa.String(length=1000), nullable=True))
    op.add_column('products', sa.Column('affiliate_url', sa.String(length=1000), nullable=True))
    op.add_column('products', sa.Column('has_free_shipping', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('is_trending', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('is_on_sale', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('in_stock', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('collected_at', sa.DateTime(), nullable=True))
    op.alter_column('products', 'title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('products', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('products', 'category',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('products', 'image_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.drop_column('products', 'images')
    op.add_column('products', sa.Column('images', postgresql.ARRAY(sa.String()), nullable=True, server_default='{}'))
    op.alter_column('products', 'product_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               nullable=True)
    op.drop_index('idx_products_category', table_name='products')
    op.drop_index('idx_products_trending', table_name='products')
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index('ix_products_category_sales', 'products', ['category', 'sales_30d'], unique=False)
    op.create_index('ix_products_deleted_at', 'products', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_products_is_trending'), 'products', ['is_trending'], unique=False)
    op.create_index('ix_products_price_sales', 'products', ['price', 'sales_30d'], unique=False)
    op.create_index(op.f('ix_products_sales_30d'), 'products', ['sales_30d'], unique=False)
    op.create_index(op.f('ix_products_sales_7d'), 'products', ['sales_7d'], unique=False)
    op.create_index(op.f('ix_products_sales_count'), 'products', ['sales_count'], unique=False)
    op.create_index('ix_products_sales_trending', 'products', ['sales_30d', 'is_trending'], unique=False)
    op.create_index(op.f('ix_products_tiktok_id'), 'products', ['tiktok_id'], unique=True)
    op.drop_column('products', 'last_scraped_at')
    op.drop_column('products', 'shop_name')
    op.drop_column('products', 'rating')
    op.drop_column('products', 'review_count')
    op.drop_column('products', 'trending_score')
    op.drop_column('products', 'status')
    op.drop_column('products', 'external_id')
    op.drop_column('products', 'shop_url')
    op.drop_column('products', 'source')
    op.drop_column('products', 'created_at')
    op.drop_column('products', 'metadata')
    op.add_column('scraping_jobs', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('scraping_jobs', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('scraping_jobs', sa.Column('products_scraped', sa.Integer(), nullable=True))
    op.alter_column('scraping_jobs', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index('idx_scraping_jobs_created_at', table_name='scraping_jobs')
    op.drop_index('idx_scraping_jobs_status', table_name='scraping_jobs')
    op.create_index('ix_scraping_jobs_status', 'scraping_jobs', ['status', 'priority'], unique=False)
    op.drop_column('scraping_jobs', 'error')
    op.drop_column('scraping_jobs', 'result')
    op.drop_column('scraping_jobs', 'params')
    op.alter_column('users', 'plan',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'free'::character varying"))
    op.drop_index('idx_users_email', table_name='users')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'verification_token')
    op.drop_column('users', 'reset_token')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'reset_token_expires')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_token_expires', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('reset_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('verification_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.alter_column('users', 'plan',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'free'::character varying"))
    op.add_column('scraping_jobs', sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.add_column('scraping_jobs', sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('scraping_jobs', sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index('ix_scraping_jobs_status', table_name='scraping_jobs')
    op.create_index('idx_scraping_jobs_status', 'scraping_jobs', ['status'], unique=False)
    op.create_index('idx_scraping_jobs_created_at', 'scraping_jobs', ['created_at'], unique=False)
    op.alter_column('scraping_jobs', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_column('scraping_jobs', 'products_scraped')
    op.drop_column('scraping_jobs', 'error_message')
    op.drop_column('scraping_jobs', 'category')
    op.add_column('products', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('source', sa.VARCHAR(length=50), server_default=sa.text("'tiktok_shop'::character varying"), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('shop_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('external_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('trending_score', sa.NUMERIC(precision=10, scale=4), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('review_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('rating', sa.NUMERIC(precision=3, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('shop_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('last_scraped_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_products_tiktok_id'), table_name='products')
    op.drop_index('ix_products_sales_trending', table_name='products')
    op.drop_index(op.f('ix_products_sales_count'), table_name='products')
    op.drop_index(op.f('ix_products_sales_7d'), table_name='products')
    op.drop_index(op.f('ix_products_sales_30d'), table_name='products')
    op.drop_index('ix_products_price_sales', table_name='products')
    op.drop_index(op.f('ix_products_is_trending'), table_name='products')
    op.drop_index('ix_products_deleted_at', table_name='products')
    op.drop_index('ix_products_category_sales', table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.create_index('idx_products_trending', 'products', [sa.text('trending_score DESC')], unique=False)
    op.create_index('idx_products_category', 'products', ['category'], unique=False)
    op.alter_column('products', 'product_url',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('products', 'images',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('products', 'image_url',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('products', 'category',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('products', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('products', 'title',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('products', 'collected_at')
    op.drop_column('products', 'deleted_at')
    op.drop_column('products', 'in_stock')
    op.drop_column('products', 'is_on_sale')
    op.drop_column('products', 'is_trending')
    op.drop_column('products', 'has_free_shipping')
    op.drop_column('products', 'affiliate_url')
    op.drop_column('products', 'video_url')
    op.drop_column('products', 'commission_rate')
    op.drop_column('products', 'sales_30d')
    op.drop_column('products', 'sales_7d')
    op.drop_column('products', 'reviews_count')
    op.drop_column('products', 'product_rating')
    op.drop_column('products', 'seller_rating')
    op.drop_column('products', 'seller_name')
    op.drop_column('products', 'subcategory')
    op.drop_column('products', 'currency')
    op.drop_column('products', 'tiktok_id')
    op.add_column('payments', sa.Column('license_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('paid_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key('payments_license_id_fkey', 'payments', 'licenses', ['license_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('payments_user_id_fkey', 'payments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('payments_external_id_key', 'payments', ['external_id'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_payments_user_id', 'payments', ['user_id'], unique=False)
    op.create_index('idx_payments_status', 'payments', ['status'], unique=False)
    op.create_index('idx_payments_external_id', 'payments', ['external_id'], unique=False)
    op.alter_column('payments', 'payment_method',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('payments', 'amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_column('payments', 'plan')
    op.add_column('licenses', sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.add_column('licenses', sa.Column('started_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('licenses', sa.Column('current_devices', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('licenses', sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'licenses', type_='foreignkey')
    op.create_foreign_key('licenses_user_id_fkey', 'licenses', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_licenses_license_key'), table_name='licenses')
    op.create_unique_constraint('licenses_license_key_key', 'licenses', ['license_key'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_licenses_user_id', 'licenses', ['user_id'], unique=False)
    op.create_index('idx_licenses_status', 'licenses', ['status'], unique=False)
    op.create_index('idx_licenses_license_key', 'licenses', ['license_key'], unique=False)
    op.alter_column('licenses', 'license_key',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('licenses', 'deactivated_at')
    op.drop_column('licenses', 'deactivation_reason')
    op.drop_column('licenses', 'last_payment_id')
    op.drop_column('licenses', 'payment_id')
    op.drop_column('licenses', 'auto_renew')
    op.drop_column('licenses', 'is_active')
    op.drop_column('licenses', 'activated_at')
    op.add_column('license_devices', sa.Column('device_info', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.add_column('license_devices', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('license_devices', sa.Column('device_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('license_devices', sa.Column('device_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('license_devices', sa.Column('last_seen', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'license_devices', type_='foreignkey')
    op.create_foreign_key('license_devices_license_id_fkey', 'license_devices', 'licenses', ['license_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_license_device', 'license_devices', type_='unique')
    op.create_unique_constraint('license_devices_license_id_device_id_key', 'license_devices', ['license_id', 'device_id'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_license_devices_license_id', 'license_devices', ['license_id'], unique=False)
    op.drop_column('license_devices', 'deactivation_reason')
    op.drop_column('license_devices', 'deactivated_at')
    op.drop_column('license_devices', 'is_active')
    op.drop_column('license_devices', 'last_seen_at')
    op.drop_column('license_devices', 'first_seen_at')
    op.drop_column('license_devices', 'app_version')
    op.drop_column('license_devices', 'hwid')
    op.add_column('copy_history', sa.Column('tokens_used', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('copy_history', sa.Column('original_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('copy_history', sa.Column('original_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('copy_history', sa.Column('generated_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('copy_history', sa.Column('generated_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('copy_history', sa.Column('template_used', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'copy_history', type_='foreignkey')
    op.create_foreign_key('copy_history_product_id_fkey', 'copy_history', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('copy_history_user_id_fkey', 'copy_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_copy_history_user_date', table_name='copy_history')
    op.create_index('idx_copy_history_user', 'copy_history', ['user_id'], unique=False)
    op.alter_column('copy_history', 'product_id',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               nullable=True)
    op.drop_column('copy_history', 'copy_text')
    op.drop_column('copy_history', 'tone')
    op.drop_column('copy_history', 'copy_type')
    op.drop_column('copy_history', 'product_title')
    op.create_table('daily_stats',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('active_users', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('copies_generated', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('new_products', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('new_users', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('revenue', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='daily_stats_pkey'),
    sa.UniqueConstraint('date', name='daily_stats_date_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('idx_daily_stats_date', 'daily_stats', ['date'], unique=False)
    op.create_table('api_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('endpoint', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('method', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('response_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='api_logs_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='api_logs_pkey')
    )
    op.create_index('idx_api_logs_user_id', 'api_logs', ['user_id'], unique=False)
    op.create_index('idx_api_logs_endpoint', 'api_logs', ['endpoint'], unique=False)
    op.create_index('idx_api_logs_created_at', 'api_logs', ['created_at'], unique=False)
    op.create_table('user_favorites',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_favorites_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_favorites_pkey'),
    sa.UniqueConstraint('user_id', 'product_id', name='user_favorites_user_id_product_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('idx_user_favorites_user_id', 'user_favorites', ['user_id'], unique=False)
    op.drop_table('payment_events')
    # ### end Alembic commands ###
