"""API Routes"""

from . import (accounting, accounts, analytics, analytics_social, api_docs,
               auth, automation, automation_dashboard, bot, campaigns, chatbot,
               chatwoot, checkout, content, copy, credits, crm, email,
               instagram, integrations, license, marketplaces, metrics,
               products, scheduler, scraper, seller_bot, social_auth,
               status_webhooks, subscription, template_library, templates,
               tiktok, users, webhooks, whatsapp, youtube)

__all__ = [
    "auth",
    "products",
    "copy",
    "license",
    "webhooks",
    "bot",
    "whatsapp",
    "chatwoot",
    "instagram",
    "tiktok",
    "youtube",
    "content",
    "scheduler",
    "integrations",
    "social_auth",
    "metrics",
    "status_webhooks",
    "checkout",
    "analytics",
    "templates",
    "accounts",
    "api_docs",
    "marketplaces",
    "subscription",
    "analytics_social",
    "chatbot",
    "automation",
    "automation_dashboard",
    "template_library",
    "email",
    "campaigns",
    "crm",
    "seller_bot",
    "accounting",
    "credits",
    "users",
    "scraper",
]
